export const InfrastructureData = [
  {
    title: "DevOps",
    href: "devops",
    description: () => <></>,
    weCanHelpWithList: [],
    technologyList: [],
  },
  {
    title: "Database Management",
    href: "databasemanagement",
    description: () => <></>,
    weCanHelpWithList: [],
    technologyList: [],
  },
  {
    title: "Infrastructure Management",
    href: "infrastructuremanagement",
    description: () => <></>,
    weCanHelpWithList: [],
    technologyList: [],
  },
  {
    title: "Virtualization",
    href: "virtualization",
    description: () => <></>,
    weCanHelpWithList: [],
    technologyList: [],
  },
  {
    title: "Storage",
    href: "=storage",
    description: () => <></>,
    weCanHelpWithList: [],
    technologyList: [],
  },
  {
    title: "Security",
    href: "security",
    description: () => <></>,
    weCanHelpWithList: [],
    technologyList: [],
  },
  {
    title: "Monitoring",
    href: "monitoring",
    description: () => <></>,
    weCanHelpWithList: [],
    technologyList: [],
  },
];
